export const ADD_ITEM = 'ADD_ITEM';

export const LOAD_ITEMS_SUCCESS = 'LOAD_ITEMS_SUCCESS';

export const LOAD_LIMITED_ITEMS_SUCCESS = 'LOAD_LIMITED_ITEMS_SUCCESS';

export const LOAD_ITEM_BY_ID_SUCCESS = 'LOAD_ITEM_BY_ID_SUCCESS';

export const LOAD_SUPPLIERS_SUCCESS = 'LOAD_SUPPLIERS_SUCCESS';

export const ADD_TO_CART = 'ADD_TO_CART';

export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';


export const BUY_ITEMS = 'BUY_ITEMS';

export const BUY_ITEMS_SUCCESS = 'BUY_ITEMS_SUCCESS';

export const LOAD_ITEMS_BY_TYPE_SUCCESS = 'LOAD_ITEMS_BY_TYPE_SUCCESS';

export const SEARCH_ITEMS_SUCCESS = 'SEARCH_ITEMS_SUCCESS';

export const SET_LOADING_MASK = 'SET_LOADING_MASK';

export const REMOVE_LOADING_MASK = 'REMOVE_LOADING_MASK';