export const ADD_ITEM = 'ADD_ITEM';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOAD_COMPLAINS_SUCCESS = 'LOAD_COMPLAINS_SUCCESS';
export const SET_LOADING_MASK = 'SET_LOADING_MASK';

export const REMOVE_LOADING_MASK = 'REMOVE_LOADING_MASK';

export const LOAD_COMPLAIN_BY_ID_SUCCESS = 'LOAD_COMPLAIN_BY_ID_SUCCESS';