export const ADD_ITEM = 'ADD_ITEM';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOAD_COMPLAINS_SUCCESS = 'LOAD_COMPLAINS_SUCCESS';
export const SET_LOADING_MASK = 'SET_LOADING_MASK';

export const REMOVE_LOADING_MASK = 'REMOVE_LOADING_MASK';

export const LOAD_COMPLAIN_BY_ID_SUCCESS = 'LOAD_COMPLAIN_BY_ID_SUCCESS';

export const LOAD_COMMENTS_BY_ID_SUCCESS = 'LOAD_COMMENTS_BY_ID_SUCCESS';

export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';

export const ADD_ADV_SUCCESS = 'ADD_ADV_SUCCESS';

export const LOG_OUT = 'LOG_OUT';

export const ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS';

export const LOAD_EVENTS_SUCCESS = 'LOAD_EVENTS_SUCCESS';

export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';

export const LOAD_SPECIES_SUCCESS = 'LOAD_SPECIES_SUCCESS';

export const LOAD_SPECIE_BY_ID_SUCCESS = 'LOAD_SPECIE_BY_ID_SUCCESS';

export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';

export const LOAD_USER_BY_ID_SUCCESS = 'LOAD_USER_BY_ID_SUCCESS';

export const LOGGED_USER = 'LOGGED_USER';

export const LOGOUT_USER = 'LOGOUT_USER';

export const LOAD_PROF_USERS_SUCCESS = 'LOAD_PROF_USERS_SUCCESS';
